# This is a TEMPLATE file. DO NOT commit actual secrets!
# Copy this to secrets.yaml and fill in your values
# Then apply with: kubectl apply -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: huggingface-secret
  namespace: climate-ai
type: Opaque
stringData:
  token: "YOUR_HUGGINGFACE_TOKEN_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: climate-ai
type: Opaque
stringData:
  token: "YOUR_GITHUB_TOKEN_HERE"
  webhook_secret: "YOUR_WEBHOOK_SECRET_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: climate-ai
type: Opaque
stringData:
  access_key: "YOUR_S3_ACCESS_KEY"
  secret_key: "YOUR_S3_SECRET_KEY"
  endpoint: "https://s3.infomaniak.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: climate-ai
type: Opaque
stringData:
  username: "climate_ai"
  password: "CHANGE_THIS_PASSWORD"
  database: "climate_ai_db"
