apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-r1-vllm
  namespace: climate-ai
  labels:
    app: deepseek-r1
    component: llm-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-r1
  template:
    metadata:
      labels:
        app: deepseek-r1
        component: llm-worker
    spec:
      containers:
      - name: vllm-deepseek
        image: vllm/vllm-openai:v0.3.0
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --model
        - deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
        - --quantization
        - gptq
        - --max-model-len
        - "32768"
        - --gpu-memory-utilization
        - "0.85"
        - --port
        - "8000"
        - --trust-remote-code
        - --enable-chunked-prefill
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "32Gi"
            cpu: "6"
            nvidia.com/gpu: "1"
          limits:
            memory: "32Gi"
            nvidia.com/gpu: "1"
        env:
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: token
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 15
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: vllm-model-cache
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 12Gi
      nodeSelector:
        node.kubernetes.io/instance-type: gpu-l4
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-service
  namespace: climate-ai
spec:
  selector:
    app: deepseek-r1
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
