apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-3-vllm
  namespace: climate-ai
  labels:
    app: llama-3-3
    component: llm-worker
spec:
  replicas: 0  # Start at 0, auto-scale on demand
  selector:
    matchLabels:
      app: llama-3-3
  template:
    metadata:
      labels:
        app: llama-3-3
        component: llm-worker
    spec:
      containers:
      - name: vllm-llama
        image: vllm/vllm-openai:v0.3.0
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --model
        - meta-llama/Llama-3.3-70B-Instruct
        - --quantization
        - awq
        - --max-model-len
        - "65536"
        - --gpu-memory-utilization
        - "0.90"
        - --port
        - "8000"
        - --trust-remote-code
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "48Gi"
            cpu: "8"
            nvidia.com/gpu: "1"
          limits:
            memory: "48Gi"
            nvidia.com/gpu: "1"
        env:
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: token
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 400
          periodSeconds: 40
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 100
          periodSeconds: 15
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: vllm-model-cache
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      nodeSelector:
        node.kubernetes.io/instance-type: gpu-l4
---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: climate-ai
spec:
  selector:
    app: llama-3-3
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llama-hpa
  namespace: climate-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llama-3-3-vllm
  minReplicas: 0  # Scale to zero when unused
  maxReplicas: 2
  metrics:
  - type: Pods
    pods:
      metric:
        name: vllm_queue_length
      target:
        type: AverageValue
        averageValue: "5"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
